name: github-conditional-demo
on: 
  push:
    branches:
      - "main"
      - "develop"
      - "features"
jobs:
  checks-condition:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo Hello
        run: |
          echo "Hello world"